### ISSUE TITLE
SCOs don't generate UUIDv5 IDs

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix-generator#20]

**Comment by rpiazza** [comment]
See #25 for an example - the windows_registry_key

This might be a different problem, but the generated id is UUIDv4, which the validator marks are invalid

**Comment by chisholm** [comment]
I don't think the spec requires UUIDv5's on SCOs.  From section 2.9:

    STIX Cyber-observable Objects SHOULD use UUIDv5 ...

So it is compliant to use UUIDv4, and much easier for the object generator implementation to do so.  I think of this as more of a nice-to-have; I'm afraid it would greatly complicate the generator to create spec compliant UUIDv5's.

I think the validator should only mark it invalid if it's enforcing the "should"s.

**Comment by rpiazza** [comment]
Closing here and creating an issue for the validator
