### ISSUE TITLE
file generated for 2.1 uses objects property in Observable Data, but not correctly

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-generator#25]
Using the objects property is deprecated in 2.1.  I'm not sure that the generator supposed to generate deprecated 2.1 content, but assuming it can, it generated something invalid

         {
            "type": "observed-data",
            "spec_version": "2.1",
            "id": "observed-data--1500c219-4588-486d-bb46-061d04084f63",
            "created_by_ref": "identity--92e5621d-57c1-40d3-a3fd-12221f72eb4c",
            "created": "2020-12-05T12:20:26.509349Z",
            "modified": "2021-10-01T07:15:23.06886Z",
            "first_observed": "2020-08-23T20:31:36.330877Z",
            "last_observed": "2021-01-12T19:26:32.747771Z",
            "number_observed": 153889452,
            "objects": {
                "windows-registry-key--8e7c5803-ab54-40f6-a028-db07391d9fc4": {
                    "type": "windows-registry-key",
                    "spec_version": "2.1",
                    "id": "windows-registry-key--8e7c5803-ab54-40f6-a028-db07391d9fc4",
                    "key": "WamlE",
                    "values": [
                        {
                            "name": "end",
                            "data": "exFxOfAaoNABU"
                        },
                        {
                            "data": "LkDIkXR",
                            "data_type": "REG_SZ"
                        },
                        {
                            "name": "kind",
                            "data": "cwwVulgG"
                        }
                    ],
                    "number_of_subkeys": 7
                }
            },

Full file attached (as a text file - silly github won't attach .json files?!):
[Indicator_based-on_Observed_Data_consent_everyone_cisa_proprietary_deny_FOUO_Report.txt](https://github.com/oasis-open/cti-stix-generator/files/6986827/Indicator_based-on_Observed_Data_consent_everyone_cisa_proprietary_deny_FOUO_Report.txt)

**Comment by chisholm** [comment]
Can you describe in what way it is invalid?

The reason it generates the "objects" property is because there is a config setting for minimizing references, which is True by default.  "object_refs" is a reference property, so it tries to generate content without that property, if it can.  In this case, it can do that by choosing the alternative property instead, which is "objects".  It is possible to switch the config setting to False.  If you do that, you will start seeing "object_refs" style observed-data SDOs (probabilistically; it's still a random choice which style to use).

**Comment by rpiazza** [comment]
First, it should be generating object_refs, not inline objects. Inline objects are deprecated as is the objects property.
It isn't wrong to generate deprecated content, but if it does, it should be valid content.  This is an example of an SCO embedded in an Observable Data object - which is just wrong.  If we want to generate deprecated content, it should be an object container, with (2.0) cyber observable objects.  The key is valid, but not in line with the SHOULD.

**Comment by chisholm** [comment]
Section 2.13 says:

    Existing Observable Data objects using Observable Containers may contain 
    SCOs as defined in this specification, but also may contain Cyber-observable
    Objects as described in version 2.0 of STIX ...

In other words, a 2.1 observable container may contain *either* 2.0 or 2.1 SCOs.  So it is a compliant thing to do.  "Should"s are not requirements.  One can violate "should"s, as long as the "musts" are adhered to.  So I don't see anything non-compliant about that content, although it does violate "should"s.  I would prefer not to violate shoulds, but it must be weighed against the implementation complexities and goals of the library.  For example, we don't have a STIX 2.0 object generator registry, and it was not a requirement to generate anything from STIX 2.0.  So the only thing we could put into observable containers was 2.1 SCOs.  We could also have simply omitted the observable container generation entirely and only generated object_refs, but our requirement was that the deprecated observable container must also occur in some generated content.  In fact, it seems to me that including content which violates the "should"s could be seen as important in testing tools' robustness.  It's still technically compliant, right?

**Comment by rpiazza** [comment]
WOW - I don't know how I missed that.  As an editor I would have argued STRONGLY against that!!!!

But it does seem to be in the spec - so once again, I guess we close this issue and create one the validator.
