### ISSUE TITLE
Generator creates a windows-registry-key SCO with invalid key property

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix-generator#26]
The validator wants a prefix on the key property - e.g.,  hkey_local_machine\\

See example file in #25

**Comment by chisholm** [comment]
I tried to use the validator once on objects created by the object generator.  I ran into this exact problem and decided the validator was being too strict.  The spec does not say keys must start with set of predefined values.  It basically only says for hives, "don't abbreviate":

    The hive portion of the key MUST be fully expanded and not truncated ...

(I think "truncate" is the wrong word; "abbreviate" or "shorten" or something like that, makes more sense.)  So I don't think the random strings the object generator creates are technically non-compliant.  The object generator doesn't generate abbreviated hive names.

**Comment by rpiazza** [comment]
I will close this here, and put the issue in the validator's issue.  Up to you if you want to issue a warning...
