### ISSUE TITLE
Add function to create bundle from mapped objects returned by generator

### ISSUE THREAD

**Issue by zrush-mitre** [oasis-open/cti-stix-generator#8]
Right now, you have to cast the mapping to a list, then use the bundle constructor from the stix library to do it. It would be nice to take care of it within the library, and possibly even give an argument for the generation to create the bundle.

**Comment by chisholm** [comment]
There is now a `utils.make_bundle()` function.  Does this help?

https://github.com/oasis-open/cti-stix-generator/blob/834cb001483bae3db877ed759b621dc3cb614723/stix2generator/utils.py#L204-L218

**Comment by zrush-mitre** [comment]
Yes I think that's a sufficient solution. Thanks!
